Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

Задание 1

Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру
Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам
Пункт 4. Пользователь по команде "ads" может добавить новую полку
Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)

In [ ]:
### РЕШЕНИЕ 1 ЗАДАНИЯ

In [30]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

"""
Пользователь по команде "p" может узнать владельца документа по его номеру
"""
def command_p(num):
    for doc in documents: 
        if num == doc['number']: result = doc['name']
        else: result = 0
    return result

"""
Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
"""
def command_s(num):
    for doc in documents: 
        for key in directories:
            if doc['number'] in directories[key]: doc['shelf'] = key
    for doc in documents: 
        if num == doc['number']: result = doc['shelf']
        else: result = 0
    return result

"""
Пользователь по команде "l" получает полные данные
"""
def command_l():
    for doc in documents: 
        for key in directories:
            if doc['number'] in directories[key]: doc['shelf'] = key
    return doc

"""
Пользователь по команде "ads" может добавить новую полку
"""
def command_ads(num):
    result = directories.setdefault(num, [])
    return result

"""
Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
"""
def command_ds(num):
    if directories[num] == []: result = directories.pop(num)
    else: result = 0
    return result

com = input('Введите команду:')
while com != 'q':
    if com == 'p':
        doc_num = input('Введите номер документа:')
        if command_p(doc_num) != 0: print(f'Владелец документа: {command_p(doc_num)}')
        else: print('Документ не найден в базе')
    elif com == 's': 
        doc_num = input('Введите номер документа:')
        if command_s(doc_num) != 0: print(f'Документ хранится на полке: {command_s(doc_num)}')
        else: print('Документ не найден в базе')
    elif com == 'l': 
        command_l() 
        for docs in documents: print(f"№: {docs['number']}, тип: {docs['type']}, владелец: {docs['name']}, полка хранения: {docs['shelf']}")
    elif com == 'ads':
        shelf_num = input('Введите номер полки:')
        if shelf_num in list(directories.keys()): print(f'Такая полка уже существует. Текущий перечень полок: {list(directories.keys())}')
        else: 
            command_ads(shelf_num) 
            print(f'Полка добавлена. Текущий перечень полок: {list(directories.keys())}')
    elif com == 'ds': 
        shelf_num = input('Введите номер полки:')
        if shelf_num not in list(directories.keys()): print(f'Такой полки не существует. Текущий перечень полок: {list(directories.keys())}')
        else:
            if command_ds(shelf_num) != 0: print(f'Полка удалена. Текущий перечень полок: {list(directories.keys())}')
            else: print(f'На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: {list(directories.keys())}')
    else: print('Неизвестная команда')
    com = input('Введите команду:')


№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


Задание 2 (необязательное)
Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

Пункт 1. Пользователь по команде «ad» может добавить новый документ в данные.
Примеры работы:

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
Результат:

Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
2.

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
Результат:

Такой полки не существует. Добавьте полку командой as.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

Пункт 2. Пользователь по команде «d» может удалить документ из данных.
Примеры работы:

Введите команду:
d

Введите номер документа:
10006
Результат:

Документ удалён.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
2.

Введите команду:
d

Введите номер документа:
123456
Результат:

Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

Пункт 3. Пользователь по команде «m» может переместить документ с полки на полку.
Примеры работы:

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
Результат:

Документ перемещён.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
2.

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
Результат:

Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2